on:
  workflow_dispatch:
jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: Delete old workflows
    steps:
      - name: Delete workflow runs
        uses: ./ # Uses an action in the root directory
        id: delete-old-workflow-runs
        with:
          repository: MikeZeDev/haruneko
          workflow: ".github/workflows/website-metrics.yml"
